extends Node3D

## Isometric 3D world renderer.
##
## Owns every piece of world geometry, the camera and the lighting. It knows
## nothing about money, airlines or aircraft states — `Main.gd` hands it plain
## render records and it draws them. That split is deliberate: the sim already
## had a clean seam (`AirportGrid.gd` contains no drawing at all), and keeping
## game rules out of here is what makes the renderer replaceable.
##
## Text is NOT drawn here. `Main._draw()` still renders every label in 2D screen
## space, positioned with `world_to_screen()`. Screen-space text stays crisp and
## upright at any camera angle, which billboarded `Label3D` does not.
##
## Rebuild policy: static geometry (tiles, runways, stands, concourses) is rebuilt
## only when the layout actually changes — `mark_layout_dirty()`. Per-frame work
## is limited to moving aircraft and recolouring stands, because stand occupancy
## changes constantly while the layout does not.

const AirportGrid = preload("res://AirportGrid.gd")
# One mesh per class, generated by scripts/generate_aircraft.py. Each is modelled
# at real-world length and normalised to screen size below, so the proportions
# between classes are truthful even though the absolute size is not.
const PLANE_MODELS := {
	"R": preload("res://assets/models/regional.glb"),
	"N": preload("res://assets/models/narrowbody.glb"),
	"W": preload("res://assets/models/widebody.glb"),
}
const MODEL_LENGTHS := {"R": 30.0, "N": 40.0, "W": 66.0}

# The model stands with its base already at y=0 and its cab at 52 units, on a
# 25.6 x 17.8 footprint. At native scale that is only 2.6x the concourse, which
# at play zoom read as a chimney on the terminal roof rather than as a landmark.
#
# Scaled up it is the same deliberate lie as PLANE_SCALE_FUDGE: 83 units is
# 1,500ft at FEET_PER_TILE, which is nonsense, but the concourse is already
# 375ft and the aircraft are oversized to match. The whole vertical scale is
# exaggerated, consistently. The footprint spills a little past its tile, which
# is why the site below wants empty neighbours.
const TOWER_MODEL := preload("res://assets/models/control-tower.glb")
const TOWER_SCALE := 1.6

# Authored to the tile grid: the hall is 6x2 tiles and the stand's 56x62 mesh sits
# inside a 3x2 footprint. Those are AirportGrid's TERMINAL_SIZE and STAND_SIZE, so
# neither needs merging or stretching.
#
# The pier is the exception, and the only building whose size is a design figure
# rather than the mesh's: it is stretched along its run to whatever CONCOURSE_SIZE
# says, out of a mesh authored 30 wide by 120.5 long.
const TERMINAL_MODEL := preload("res://assets/models/terminal.glb")
const CONCOURSE_MODEL := preload("res://assets/models/concourse.glb")
const CONCOURSE_MODEL_LEN := 120.5
const CONCOURSE_MODEL_W := 30.0
const STAND_MODEL := preload("res://assets/models/stand.glb")

# Landside. The road tile is a 2-unit square laid out like the taxiway kit — its
# carriageway runs along local z — so it scales to the tile the same way.
#
# There is only the ONE road piece. Corners, tees and crossroads are built by
# laying it twice, once per axis, and dropping whichever of its markings would be
# wrong for that junction (see _build_road_tile). A curved piece was tried and
# does not fit the grid: its arc is centred on the tile CORNER with a centreline
# radius of about 1.45 tiles, so the carriageway leaves the tile edge nearly half
# a tile off centre and is roughly half the straight's width. A one-tile curve
# would need the arc centred on the corner at centreline radius 1.0, meeting both
# edges at their midpoints, and the same 1.7-unit carriageway.
const ROAD_MODEL := preload("res://assets/models/road.glb")
const ROAD_MODEL_TILE := 2.0
const ROAD_SCALE := AirportGrid.TILE / ROAD_MODEL_TILE
const ROAD_PRE := Transform3D(
	Basis(Vector3(ROAD_SCALE, 0.0, 0.0), Vector3(0.0, ROAD_SCALE, 0.0),
		Vector3(0.0, 0.0, ROAD_SCALE)),
	Vector3.ZERO)

# The car park is a whole multi-storey ramp, cars and all, authored at world scale
# — 31.5 units across a 32-unit tile — so it needs no scaling, only turning so its
# ramp faces the road.
const PARKING_MODEL := preload("res://assets/models/parking.glb")

# --- projection -------------------------------------------------------------

# 2D world coords map to 3D as (x, height, y): the sim's screen-down axis becomes
# ground-depth, so every existing Vector2 in the simulation is usable unchanged.
static func w3(p: Vector2, y: float = 0.0) -> Vector3:
	return Vector3(p.x, y, p.y)


const ISO_PITCH_DEG := -35.264
const ISO_YAW_DEG := 45.0

# --- palette (carried over from the old 2D _draw(), so the game still reads as
# itself — only the projection and the addition of height changed) ------------

# Ground colours are per-region now (see Regions.TERRAIN); these are the fallback
# used before a region has been chosen, and match the original temperate look.
const COL_OUTSIDE := Color(0.227, 0.361, 0.227)
const COL_FIELD := Color(0.19, 0.31, 0.19)
const COL_TAXIWAY := Color(0.40, 0.40, 0.43)
const COL_TERMINAL := Color(0.36, 0.33, 0.45)
const COL_TERMINAL_EDGE := Color(0.62, 0.58, 0.78)
const COL_RUNWAY := Color(0.28, 0.28, 0.30)
const COL_STAND_FREE := Color(0.18, 0.42, 0.18)
const COL_STAND_BUSY := Color(0.75, 0.32, 0.25)
const COL_STAND_ORPHAN := Color(0.45, 0.35, 0.15)
const COL_MARKING := Color(0.87, 0.87, 0.87)

# --- heights ----------------------------------------------------------------
# Coplanar surfaces z-fight, so each layer gets its own band rather than an
# epsilon nudge. Units match the 2D game exactly (1 unit = 1px, TILE = 32).

const H_PAVEMENT := 1.2
const H_STAND := 1.6
const H_MARKING := 2.0
const H_TERMINAL := 20.0
const H_KERB := 2.4
const H_GHOST := 3.0

# --- aircraft scale ---------------------------------------------------------
#
# The model is 65.8 units nose-to-tail at real-world scale. At FEET_PER_TILE=600
# that is 0.36 of a tile, effectively invisible, so aircraft are drawn oversized
# exactly as the old 2D renderer did (a 21px narrowbody against a 32px tile).
#
# This is a legibility lie in the same family as REVENUE_SCALE, and it lives in
# ONE constant for the same reason — tune it here, do not spread compensating
# tweaks through the renderer.
const PLANE_LENGTH_PX := 21.0

const PLANE_SCALE_FUDGE := 2.0

# Airside/landside width hierarchy: runway > taxiway > road. Real proportions
# are roughly 45m / 23m / 7m, and a full-tile road read as wide as a taxiway,
# which made the landside look like more apron. A taxiway is locked to exactly
# one tile by the grid, so it is the fixed middle of the ratio and the other two
# move around it.
const RUNWAY_WIDTH_TILES := 1.2

# Shared with Main's help overlay so the two listings cannot drift apart.
const CAMERA_HINT := "middle-drag pan · right-drag rotate · wheel zoom · arrows pan · , . rotate 45° · Home reset"

var grid

var _cam: Camera3D
var _yaw_node: Node3D
var _pitch_node: Node3D
var _static_root: Node3D
var _plane_root: Node3D
var _ghost_root: Node3D

var _plane_nodes := {}
var _stand_nodes := {}
var _mats := {}
var _livery_cache := {}

var _terrain: Dictionary = {}
var _weather_kind := ""
var _weather: CPUParticles3D

var _ground_root: Node3D
var _scenery_root: Node3D
var _tiles_root: Node3D
var _terminal_root: Node3D
var _runway_root: Node3D
var _stand_root: Node3D
var _tower_root: Node3D
var _tower_count := 0

var _scenery_built := false
var _ground_mask := -1

var _yaw_deg := ISO_YAW_DEG
var _pan := Vector2.ZERO
var _zoom := 1.0
var _layout_dirty := true
var _ghost_sig := ""
var _panning := false
var _orbiting := false
var _hint: Label


func _ready() -> void:
	_build_environment()
	_build_camera()
	_static_root = Node3D.new()
	add_child(_static_root)
	# One root per rebuild tier, so a layout change never touches scenery.
	for holder in ["_ground_root", "_scenery_root", "_tiles_root", "_terminal_root",
			"_runway_root", "_stand_root", "_tower_root"]:
		var n := Node3D.new()
		_static_root.add_child(n)
		set(holder, n)
	_plane_root = Node3D.new()
	add_child(_plane_root)
	_ghost_root = Node3D.new()
	add_child(_ghost_root)
	_build_hint()


# Camera controls are invisible otherwise — there is nothing on screen to
# suggest the view can move at all. Sits just above the build toolbar.
func _build_hint() -> void:
	var layer := CanvasLayer.new()
	add_child(layer)
	_hint = Label.new()
	_hint.position = Vector2(12, 648)
	_hint.add_theme_font_size_override("font_size", 12)
	_hint.add_theme_color_override("font_color", Color(1, 1, 1, 0.5))
	_hint.text = "CAMERA — " + CAMERA_HINT
	layer.add_child(_hint)


# Placed by Main's HUD layout rather than by a constant here: the hint belongs to
# the bottom bar, and only Main knows where that bar ends up for a given window.
func set_hint_position(p: Vector2) -> void:
	if _hint != null:
		_hint.position = p


func attach(g) -> void:
	grid = g
	# The camera is built before the grid exists, so its pivot was placed at the
	# world origin. Re-apply now that there is a field to centre on.
	_apply_camera()
	mark_layout_dirty()


func mark_layout_dirty() -> void:
	_layout_dirty = true


# --- materials --------------------------------------------------------------

func _mat(key: String, c: Color, transparent: bool = false) -> StandardMaterial3D:
	if _mats.has(key):
		return _mats[key]
	var m := StandardMaterial3D.new()
	m.albedo_color = c
	m.roughness = 0.92
	m.metallic = 0.0
	if transparent:
		m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
		m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	_mats[key] = m
	return m


# One shared unit cube, scaled per instance, rather than a fresh BoxMesh per
# call. A full rebuild made on the order of a thousand of those, and pushing that
# many new vertex buffers to the server cost more than the node churn did.
#
# Node3D applies scale before rotation, so scaling a unit box reproduces the old
# `box.size = size` transform exactly. Box normals stay axis-aligned under
# axis-aligned scale, so shading is unchanged too.
var _unit_box: BoxMesh


func _slab(parent: Node3D, size: Vector3, centre: Vector3, mat: Material, yaw: float = 0.0) -> MeshInstance3D:
	if _unit_box == null:
		_unit_box = BoxMesh.new()
		_unit_box.size = Vector3.ONE
	var mi := MeshInstance3D.new()
	mi.mesh = _unit_box
	mi.material_override = mat
	mi.position = centre
	mi.scale = size
	mi.rotation = Vector3(0.0, yaw, 0.0)
	parent.add_child(mi)
	return mi


# --- camera + lighting ------------------------------------------------------

# --- batching ---------------------------------------------------------------
#
# Per-tile geometry is accumulated by (mesh, material) and flushed into one
# MultiMeshInstance3D per group. Accumulate-then-flush keeps the fill a single
# tight pass with no capacity juggling inside the build loops.

var _batches := {}
var _unit_cone: CylinderMesh
var _unit_cyl: CylinderMesh
var _unit_sphere: SphereMesh


func _mesh_for(shape: String) -> Mesh:
	match shape:
		"cone":
			if _unit_cone == null:
				_unit_cone = CylinderMesh.new()
				_unit_cone.top_radius = 0.0
				_unit_cone.bottom_radius = 0.5
				_unit_cone.height = 1.0
				# Must match the old _cone() silhouette exactly.
				_unit_cone.radial_segments = 7
			return _unit_cone
		"cyl":
			if _unit_cyl == null:
				_unit_cyl = CylinderMesh.new()
				_unit_cyl.top_radius = 0.5
				_unit_cyl.bottom_radius = 0.5
				_unit_cyl.height = 1.0
				_unit_cyl.radial_segments = 6
			return _unit_cyl
		"sphere":
			if _unit_sphere == null:
				_unit_sphere = SphereMesh.new()
				_unit_sphere.radius = 0.5
				_unit_sphere.height = 1.0
			return _unit_sphere
	if _unit_box == null:
		_unit_box = BoxMesh.new()
		_unit_box.size = Vector3.ONE
	return _unit_box


# Basis must be rotation * scale (local axes). Basis.scaled() post-multiplies,
# which scales along GLOBAL axes and silently skews every rotated runway into
# something that still looks plausible.
func _add(key: String, shape: String, mat: Material, size: Vector3, centre: Vector3,
		yaw: float = 0.0) -> void:
	var b := Basis(Vector3.UP, yaw) * Basis.from_scale(size)
	if not _batches.has(key):
		_batches[key] = {"shape": shape, "mat": mat, "x": []}
	(_batches[key]["x"] as Array).append(Transform3D(b, centre))


func _flush_batches(root: Node3D) -> void:
	for key in _batches:
		var b: Dictionary = _batches[key]
		var xforms: Array = b["x"]
		if xforms.is_empty():
			continue
		var mm := MultiMesh.new()
		# Format flags must be set BEFORE instance_count — changing either
		# afterwards wipes the buffer.
		mm.transform_format = MultiMesh.TRANSFORM_3D
		mm.mesh = _mesh_for(b["shape"])
		mm.instance_count = xforms.size()
		for i in xforms.size():
			mm.set_instance_transform(i, xforms[i])
		var mmi := MultiMeshInstance3D.new()
		mmi.multimesh = mm
		mmi.material_override = b["mat"]
		# Without an explicit AABB the server recomputes bounds across every
		# instance each time the buffer changes — the exact O(n) cost being
		# removed here.
		var g: Rect2 = grid.grid_rect()
		mmi.custom_aabb = AABB(
			Vector3(g.position.x - 2000.0, -400.0, g.position.y - 2000.0),
			Vector3(g.size.x + 4000.0, 900.0, g.size.y + 4000.0))
		root.add_child(mmi)
	_batches.clear()


# --- authored models -------------------------------------------------------
#
# The .glb models are not one mesh each: the taxiway pieces carry 35 to 82
# MeshInstance3D children, the stand 68, the tower 144. Instantiating one scene
# per placed object is what took the layout rebuild from 294 nodes and 0.34ms to
# 1740 nodes and 14ms — a cost paid on every single tile placement, because
# mark_layout_dirty() rebuilds the lot.
#
# So each model is welded ONCE into a single ArrayMesh, one surface per material,
# and every placement of it becomes an instance transform in a MultiMesh. A
# painted taxiway tile then costs a Transform3D rather than a subtree, and the
# whole taxiway system is five nodes however much pavement there is.
#
# `pre` is a transform baked into the weld — used for the taxiway kit, whose
# pieces need scaling to the tile and backing up by half their own length. It is
# part of the cache key's meaning, so a model welded with two different `pre`
# values needs two different keys.
#
# Anything varying per placement goes in the INSTANCE transform instead, which is
# how a pier stretches to its own length off a shared mesh.
#
# These survive set_terrain(), unlike the _mats cache it clears: model materials
# come out of the .glb and are never rebuilt against the terrain palette.
var _welded := {}
var _model_xforms := {}


# `remap` optionally repaints or drops individual meshes as they are welded. It
# takes (node name, material name, bounds in the welded frame) and returns the
# material name to use, or "" to drop the mesh. It only runs on a cache miss, so
# whatever varies it MUST also vary the key.
func _add_model(key: String, scene: PackedScene, pre: Transform3D, xf: Transform3D,
		remap := Callable(), shadows := true) -> void:
	if not _model_xforms.has(key):
		_model_xforms[key] = {
			"scene": scene, "pre": pre, "remap": remap, "shadows": shadows, "x": [],
		}
	(_model_xforms[key]["x"] as Array).append(xf)


func _welded_mesh(key: String, scene: PackedScene, pre: Transform3D,
		remap := Callable()) -> ArrayMesh:
	if _welded.has(key):
		return _welded[key]
	var src: Node3D = scene.instantiate()
	# Collected first, grouped second: a remap can send a mesh to a material that
	# has not been walked yet, and resolving names against a half-filled table
	# would silently depend on the order the .glb happens to list its nodes in.
	var parts: Array = []
	var by_name := {}
	_collect_parts(src, pre, parts, by_name)

	var by_mat := {}
	# Materials are dictionary keys, so surface order would otherwise be whatever
	# the hash happens to give. Kept explicit, so a rebuild cannot reorder a
	# model's markings under its own pavement.
	var order: Array = []
	for p in parts:
		var mat: Material = p["mat"]
		if remap.is_valid():
			var want: String = remap.call(p["node"], p["name"], p["box"])
			if want == "":
				continue
			mat = by_name.get(want, mat)
		if not by_mat.has(mat):
			var st := SurfaceTool.new()
			st.begin(Mesh.PRIMITIVE_TRIANGLES)
			by_mat[mat] = st
			order.append(mat)
		(by_mat[mat] as SurfaceTool).append_from(p["mesh"], p["surface"], p["xf"])

	var out := ArrayMesh.new()
	for mat in order:
		(by_mat[mat] as SurfaceTool).commit(out)
		out.surface_set_material(out.get_surface_count() - 1, mat)
	# Never entered the tree, so free() rather than queue_free().
	src.free()
	_welded[key] = out
	return out


func _collect_parts(n: Node, xf: Transform3D, parts: Array, by_name: Dictionary) -> void:
	var here := xf
	if n is Node3D:
		here = xf * (n as Node3D).transform
	if n is MeshInstance3D:
		var mi: MeshInstance3D = n
		var m: Mesh = mi.mesh
		if m != null:
			for s in m.get_surface_count():
				var mat: Material = mi.get_active_material(s)
				var nm := "" if mat == null else mat.resource_name
				if nm != "" and not by_name.has(nm):
					by_name[nm] = mat
				parts.append({
					"node": String(mi.name), "name": nm, "mat": mat,
					"mesh": m, "surface": s, "xf": here,
					"box": here * mi.get_aabb(),
				})
	for c in n.get_children():
		_collect_parts(c, here, parts, by_name)


# No material_override, unlike _flush_batches: a welded mesh carries a surface per
# material of its own, which is what lets one MultiMesh stand in for a model that
# was eighty separate meshes.
func _flush_models(root: Node3D) -> void:
	for key in _model_xforms:
		var b: Dictionary = _model_xforms[key]
		var xforms: Array = b["x"]
		if xforms.is_empty():
			continue
		var mm := MultiMesh.new()
		# Format before instance_count — changing it afterwards wipes the buffer.
		mm.transform_format = MultiMesh.TRANSFORM_3D
		mm.mesh = _welded_mesh(key, b["scene"], b["pre"], b["remap"])
		mm.instance_count = xforms.size()
		for i in xforms.size():
			mm.set_instance_transform(i, xforms[i])
		var mmi := MultiMeshInstance3D.new()
		mmi.multimesh = mm
		if not b["shadows"]:
			mmi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		var g: Rect2 = grid.grid_rect()
		mmi.custom_aabb = AABB(
			Vector3(g.position.x - 2000.0, -400.0, g.position.y - 2000.0),
			Vector3(g.size.x + 4000.0, 900.0, g.size.y + 4000.0))
		root.add_child(mmi)
	_model_xforms.clear()


func _build_environment() -> void:
	var env := Environment.new()
	env.background_mode = Environment.BG_COLOR
	env.background_color = COL_OUTSIDE
	env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.ambient_light_color = Color(0.58, 0.65, 0.75)
	env.ambient_light_energy = 0.6

	var we := WorldEnvironment.new()
	we.environment = env
	add_child(we)

	# Angled across the field rather than down the view axis, so concourses and
	# tails throw shadows that describe their shape instead of hiding behind them.
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-52.0, -130.0, 0.0)
	sun.light_energy = 1.15
	sun.shadow_enabled = true
	sun.directional_shadow_max_distance = 4000.0
	add_child(sun)


func _build_camera() -> void:
	# Nested yaw/pitch nodes rather than one Euler triple: rotation order on a
	# combined Vector3 is easy to get subtly wrong, and orbiting then reduces to
	# "spin the yaw node".
	_yaw_node = Node3D.new()
	add_child(_yaw_node)
	_pitch_node = Node3D.new()
	_yaw_node.add_child(_pitch_node)

	_cam = Camera3D.new()
	_cam.projection = Camera3D.PROJECTION_ORTHOGONAL
	# Ortho has no perspective falloff, so distance only affects clipping — keep
	# it well clear of the field from every orbit position.
	_cam.position = Vector3(0.0, 0.0, 2500.0)
	_cam.near = 1.0
	_cam.far = 8000.0
	_pitch_node.add_child(_cam)

	_apply_camera()


# The HUD sidebar and the bottom toolbar sit on top of the 3D view, so the
# usable window is smaller than the viewport. Framing against the full viewport
# buries a third of the airport under the UI.
const UI_MARGIN_RIGHT := 416.0
const UI_MARGIN_BOTTOM := 232.0
const UI_MARGIN_TOP := 96.0


func _visible_rect() -> Rect2:
	var vp: Vector2i = get_viewport().size
	return Rect2(0.0, UI_MARGIN_TOP,
		float(vp.x) - UI_MARGIN_RIGHT, float(vp.y) - UI_MARGIN_BOTTOM - UI_MARGIN_TOP)


func _default_size() -> float:
	if grid == null:
		return 700.0
	# Owned land, not the whole grid: otherwise the game opens zoomed out over
	# tracts the player does not own yet.
	var b: Rect2 = grid.owned_rect()
	# An iso-projected W x D rect spans (W+D)*cos45 horizontally and that same
	# span times sin(pitch) vertically.
	var span: float = b.size.x + b.size.y
	var horiz: float = span * cos(deg_to_rad(45.0))
	var vert: float = horiz * sin(-deg_to_rad(ISO_PITCH_DEG))

	# Solve for world-units-per-pixel that fits both axes inside the un-obscured
	# area, then scale back up to the full viewport height, which is what
	# Camera3D.size actually measures.
	var vis := _visible_rect()
	var vp: Vector2i = get_viewport().size
	var k: float = maxf(horiz / maxf(vis.size.x, 1.0), vert / maxf(vis.size.y, 1.0))
	return k * float(vp.y) * 1.06


func _apply_camera() -> void:
	var centre := Vector2.ZERO
	if grid != null:
		var b: Rect2 = grid.owned_rect()
		centre = b.position + b.size * 0.5
	_yaw_node.position = w3(centre + _pan, 0.0)
	_yaw_node.rotation_degrees = Vector3(0.0, _yaw_deg, 0.0)
	_pitch_node.rotation_degrees = Vector3(ISO_PITCH_DEG, 0.0, 0.0)
	_cam.size = _default_size() * _zoom

	# Shift the frustum so the field centres in the un-obscured area rather than
	# behind the sidebar. h_offset moves the camera, so the image moves opposite.
	var vp: Vector2i = get_viewport().size
	var vis := _visible_rect()
	var k: float = _cam.size / float(maxi(vp.y, 1))
	var d: Vector2 = vis.position + vis.size * 0.5 - Vector2(vp) * 0.5
	_cam.h_offset = -d.x * k
	_cam.v_offset = d.y * k


func reset_camera() -> void:
	_yaw_deg = ISO_YAW_DEG
	_pan = Vector2.ZERO
	_zoom = 1.0
	_apply_camera()


# --- picking / projection ---------------------------------------------------

# Screen point to a position on the airport's ground plane. This replaces the
# old renderer's direct use of the mouse position: under a 2D top-down view
# screen space *was* world space, which is exactly the assumption 3D breaks.
func screen_to_world(screen_pos: Vector2) -> Vector2:
	if _cam == null:
		return Vector2.ZERO
	var from: Vector3 = _cam.project_ray_origin(screen_pos)
	var dir: Vector3 = _cam.project_ray_normal(screen_pos)
	# Intersect the pavement plane rather than y=0, so the cursor lines up with
	# the surfaces the player is actually aiming at.
	if absf(dir.y) < 0.00001:
		return Vector2.ZERO
	var t: float = (H_PAVEMENT - from.y) / dir.y
	var hit: Vector3 = from + dir * t
	return Vector2(hit.x, hit.z)


func world_to_screen(w: Vector2, height: float = 0.0) -> Vector2:
	if _cam == null:
		return Vector2.ZERO
	return _cam.unproject_position(w3(w, height))


# --- static geometry --------------------------------------------------------

# Rebuilds are split by how expensive a category is to regenerate, not by who
# changed it. The public API stays `mark_layout_dirty()` with no arguments on
# purpose: the caller cannot know which categories it invalidated. Painting a
# taxiway three tiles from a runway flips that runway's centreline from red to
# white via runway_is_usable(), so any caller-supplied category would be wrong.
func rebuild_if_dirty() -> void:
	if grid == null:
		return

	# Session-static: scenery only changes when the region does.
	if not _scenery_built:
		_scenery_built = true
		_rebuild_scenery()

	# Rarely dirty: ground follows land ownership, and so does the framing.
	var mask := _owned_mask()
	if mask != _ground_mask:
		_ground_mask = mask
		_rebuild_ground()
		_apply_camera()

	if not _layout_dirty:
		return
	_layout_dirty = false
	_rebuild_layout()


# Exact and cheap — tracts are only ever added by buy_tract() or replaced
# wholesale by from_dict(), and a bitmask catches both without hashing.
func _owned_mask() -> int:
	var m := 0
	for i in grid.owned_tracts:
		m |= 1 << int(i)
	return m


func _clear(root: Node3D) -> void:
	# free(), not queue_free(): the frees would otherwise be deferred to end of
	# frame while sync_stands() runs against _stand_nodes in this same frame.
	for c in root.get_children():
		root.remove_child(c)
		c.free()


func _rebuild_scenery() -> void:
	_clear(_scenery_root)
	_build_terrain_features()
	_build_compass()
	_flush_batches(_scenery_root)


func _rebuild_ground() -> void:
	_clear(_ground_root)
	_build_ground()


func _rebuild_layout() -> void:
	_clear(_tiles_root)
	_clear(_terminal_root)
	_clear(_runway_root)
	_clear(_stand_root)
	_clear(_tower_root)
	_stand_nodes.clear()

	_build_tiles()
	_flush_batches(_tiles_root)
	_flush_models(_tiles_root)
	_build_terminals()
	_flush_batches(_terminal_root)
	_flush_models(_terminal_root)
	_build_runways()
	_flush_batches(_runway_root)
	# The stand PADS stay individual nodes — sync_stands() recolours them every
	# frame, and batching would force per-instance colour. Only the model batches.
	_build_stands()
	_flush_models(_stand_root)
	_build_tower()
	_flush_models(_tower_root)


# Terrain is cosmetic and arrives only once the player picks a region, which is
# after the renderer already exists — so it is applied late.
#
# This MUST invalidate every tier. _mats.clear() orphans the cached materials
# while existing batches still hold material_override references to the old
# objects, so anything not rebuilt would silently keep the fallback colours.
func set_terrain(t: Dictionary) -> void:
	_terrain = t
	_mats.clear()
	_scenery_built = false
	_ground_mask = -1
	mark_layout_dirty()


func _terrain_color(key: String, fallback: Color) -> Color:
	if _terrain.has(key):
		return _terrain[key]
	return fallback


func _build_ground() -> void:
	var r: Rect2 = grid.grid_rect()
	# A skirt well beyond the buildable area, so the field does not simply end in
	# mid-air at this camera angle.
	_slab(_ground_root, Vector3(r.size.x * 4.0, 2.0, r.size.y * 4.0),
		w3(r.position + r.size * 0.5, -2.0),
		_mat("skirt", _terrain_color("surround", COL_OUTSIDE)))
	# Owned land is drawn as the airport's own ground; buyable tracts are drawn
	# darker and a touch lower, so the boundary of the property is legible
	# without needing an overlay.
	var field := _terrain_color("field", COL_FIELD)
	var field_mat := _mat("field", field)
	var raw_mat := _mat("rawland", field.darkened(0.34).lerp(Color(0.28, 0.26, 0.20), 0.25))

	_tract_slab(AirportGrid.START_TRACT, field_mat, 0.0)
	for i in AirportGrid.TRACTS.size():
		var tr: Rect2i = AirportGrid.TRACTS[i]
		if grid.owned_tracts.has(i):
			_tract_slab(tr, field_mat, 0.0)
		else:
			_tract_slab(tr, raw_mat, -0.7)

	_build_terrain_features()
	_build_compass()


func _tract_slab(r: Rect2i, mat: Material, y: float) -> void:
	var t: float = AirportGrid.TILE
	var pos: Vector2 = AirportGrid.ORIGIN + Vector2(r.position) * t
	var size: Vector2 = Vector2(r.size) * t
	_slab(_ground_root, Vector3(size.x, 2.0, size.y), w3(pos + size * 0.5, y), mat)


# Scatter whatever the region grows outside the fence. Deterministic from the
# terrain name so the skyline is stable across rebuilds — a fresh scatter every
# time a taxiway is placed would make the horizon crawl.
func _build_terrain_features() -> void:
	if _terrain.is_empty():
		return
	var kind: String = _terrain.get("feature", "none")
	if kind == "none":
		return

	var rng := RandomNumberGenerator.new()
	rng.seed = hash(str(_terrain.get("name", "x")))

	var r: Rect2 = grid.grid_rect()
	# Keep a clear margin so nothing sprouts on the apron, and stay inside the
	# skirt so features never float off its edge.
	var inner := r.grow(AirportGrid.TILE * 1.5)
	var outer := r.grow(AirportGrid.TILE * 13.0)
	var body := _mat("feat", _terrain_color("feature_color", COL_OUTSIDE))
	var accent := _mat("feataccent", _terrain_color("accent", COL_OUTSIDE))

	var want: int = int(_terrain.get("density", 100))
	var placed := 0
	var guard := 0
	while placed < want and guard < want * 12:
		guard += 1
		var p := Vector2(
			rng.randf_range(outer.position.x, outer.end.x),
			rng.randf_range(outer.position.y, outer.end.y))
		if inner.has_point(p):
			continue
		_spawn_feature(kind, p, rng, body, accent)
		placed += 1


func _spawn_feature(kind: String, p: Vector2, rng: RandomNumberGenerator,
		body: Material, accent: Material) -> void:
	match kind:
		"mountains":
			# Big enough to actually ring the airport rather than read as rubble.
			var h: float = rng.randf_range(90.0, 240.0)
			var rad: float = h * rng.randf_range(0.45, 0.75)
			_cone(p, rad, h, body)
			# Snow line only on the taller peaks, which is what makes a range
			# read as a range instead of a row of identical cones.
			if h > 150.0:
				_cone(p + Vector2(0.0, 0.0), rad * 0.34, h * 0.3, accent, h * 0.72)
		"conifers":
			var th: float = rng.randf_range(16.0, 30.0)
			_cone(p, th * rng.randf_range(0.24, 0.34), th, body)
		"palms":
			var ph: float = rng.randf_range(20.0, 34.0)
			_cylinder(p, 1.1, ph, accent)
			_cone(p, 7.0, 8.0, body, ph * 0.86)
		"mesas":
			var mh: float = rng.randf_range(14.0, 34.0)
			var mw: float = mh * rng.randf_range(0.8, 1.5)
			_add("mesa", "box", body, Vector3(mw, mh, mw * rng.randf_range(0.6, 1.0)),
				w3(p, mh * 0.5), rng.randf_range(0.0, TAU))
		"dunes":
			var dh: float = rng.randf_range(6.0, 16.0)
			var dr: float = dh * rng.randf_range(2.2, 4.0)
			# SphereMesh already took radius and height independently, i.e. it was
			# an ellipsoid; non-uniform scale of a unit sphere is the same shape.
			_add("dune", "sphere", body, Vector3(dr * 2.0, dh * 2.0, dr * 2.0), w3(p, 0.0))
		"scrub":
			var sh: float = rng.randf_range(3.0, 7.0)
			_add("scrub", "sphere", body, Vector3(sh * 2.0, sh * 1.4, sh * 2.0), w3(p, sh * 0.4))


# Scenery cones and cylinders batch against shared unit meshes. Curved surfaces
# do get skewed normals under non-uniform scale, but the old code already set
# radius and height independently, so the result is identical.
func _cone(p: Vector2, radius: float, height: float, mat: Material, base: float = 0.0) -> void:
	_add("cone_" + str(mat.get_instance_id()), "cone", mat,
		Vector3(radius * 2.0, height, radius * 2.0), w3(p, base + height * 0.5))


func _cylinder(p: Vector2, radius: float, height: float, mat: Material) -> void:
	_add("cyl_" + str(mat.get_instance_id()), "cyl", mat,
		Vector3(radius * 2.0, height, radius * 2.0), w3(p, height * 0.5))


# A compass rose painted on the field's north-west corner. World -y is north (the
# same convention runway designators use), and because it is real ground geometry
# rather than a HUD widget it stays truthful as the camera rotates.
#
# Sits on the surround just off the north-west corner, clear of every buildable
# tile. It was briefly painted inside the field, which put a permanent decal on
# land the player is meant to build on.
func _build_compass() -> void:
	var r: Rect2 = grid.grid_rect()
	# West of x=0, so it is outside every tract the player can ever own. Offset
	# down rather than diagonally out: in this projection an offset along the
	# north-west diagonal pushes past the camera's framing and is never seen,
	# whereas a due-west one stays at the same screen depth.
	var c := Vector2(r.position.x - AirportGrid.TILE * 2.2, r.position.y + AirportGrid.TILE * 3.0)
	var ink := _mat("compass", Color(0.93, 0.95, 0.93, 0.85), true)

	var ring := TorusMesh.new()
	ring.inner_radius = 30.0
	ring.outer_radius = 33.0
	var rm := MeshInstance3D.new()
	rm.mesh = ring
	rm.material_override = ink
	rm.position = w3(c, H_MARKING)
	_scenery_root.add_child(rm)

	# North needle, then a shorter cross-bar for the other three points.
	_slab(_scenery_root, Vector3(4.0, 0.6, 54.0), w3(c + Vector2(0.0, -6.0), H_MARKING), ink)
	_slab(_scenery_root, Vector3(40.0, 0.6, 3.0), w3(c, H_MARKING), ink)

	var n := Label3D.new()
	n.text = "N"
	n.font_size = 96
	n.pixel_size = 0.42
	n.modulate = Color(0.95, 0.97, 0.95)
	n.billboard = BaseMaterial3D.BILLBOARD_DISABLED
	n.double_sided = true
	n.no_depth_test = false
	n.rotation_degrees = Vector3(-90.0, 0.0, 0.0)
	n.position = w3(c + Vector2(0.0, -46.0), H_MARKING)
	_scenery_root.add_child(n)


func _build_tiles() -> void:
	var t: float = AirportGrid.TILE
	for cell in grid.tiles:
		var type: int = grid.tile_type(cell)
		var centre: Vector2 = grid.cell_to_world(cell)

		match type:
			AirportGrid.TileType.TAXIWAY:
				_build_taxiway_tile(cell, centre)
			AirportGrid.TileType.ROAD:
				_build_road_tile(cell, centre)
			AirportGrid.TileType.PARKING:
				_build_parking_tile(cell, centre)
			AirportGrid.TileType.CONCOURSE:
				pass  # Merged into runs below, so a concourse reads as one building.


# --- taxiways ---------------------------------------------------------------
#
# Autotiled from a five-piece kit. Each piece is a 44-unit square authored with
# its pavement running north-south and its origin at the centre of its NORTH
# edge, so a piece is positioned at its tile's north edge and rotated about that
# point. Model -z/-x line up with grid north/west, which is why the mask below
# can be read straight off the grid with no axis translation.
#
# Which sides each piece opens on, at zero rotation. Measured off the pavement
# meshes' own bounds rather than trusted from the file names — `corner` opens
# north and west, which the naming did not make obvious.
const TX_N := 1
const TX_E := 2
const TX_S := 4
const TX_W := 8
const TX_PIECES := [
	# mask, model, and whether a lone stub should use it
	{"mask": TX_S, "name": "end"},
	{"mask": TX_N | TX_S, "name": "mid"},
	{"mask": TX_N | TX_W, "name": "corner"},
	{"mask": TX_N | TX_S | TX_W, "name": "tee"},
	{"mask": TX_N | TX_E | TX_S | TX_W, "name": "cross"},
]
const TX_MODELS := {
	"mid": preload("res://assets/models/taxiway/mid.glb"),
	"end": preload("res://assets/models/taxiway/end.glb"),
	"corner": preload("res://assets/models/taxiway/corner.glb"),
	"tee": preload("res://assets/models/taxiway/tee.glb"),
	"cross": preload("res://assets/models/taxiway/cross.glb"),
}
# The piece is a 44-unit square whose pavement is the middle 23 units; the rest
# is shoulder. Every other asset in the game is authored at the world's 32 units
# per tile — the stand is 62.7 across two, the pier 30 across one, the hall about
# 31 — so the taxiway kit is the odd one out at 44.
#
# Squashing it to fit the tile is what made the taxiways look toy: it took the
# pavement down to 17 units against a 64-unit stand and a 42-unit aircraft. At
# native scale the pavement is 23 units, about seventy per cent of a tile, which
# is the same proportion every other asset was drawn to. The shoulders then
# overrun into the neighbouring cell, which is harmless — they are margin, and
# neighbouring pieces' shoulders are the same material at the same height.
const TX_MODEL_TILE := 44.0
# Must tile EXACTLY, so this is forced: one piece covers one cell and no more.
# Rendering at native scale to get a wider pavement overlapped every neighbour
# by 12 units, and since each piece carries its own centreline, edge stripes and
# lights, the overlap drew all of them two and three times over — the apron
# turned into a scribble of doubled markings. Whatever the pavement ends up
# looking like, it cannot be bought by letting the pieces overrun each other.
const TX_SCALE := AirportGrid.TILE / TX_MODEL_TILE
# Baked into the weld rather than applied per tile: scaled to the tile, and backed
# up by half its own length — not half a tile — because the piece hangs south from
# its origin and has to end up centred on its cell once rotated.
const TX_PRE := Transform3D(
	Basis(Vector3(TX_SCALE, 0.0, 0.0), Vector3(0.0, TX_SCALE, 0.0), Vector3(0.0, 0.0, TX_SCALE)),
	Vector3(0.0, 0.0, -TX_MODEL_TILE * TX_SCALE * 0.5))


# One yaw step is +90 degrees about Y, which carries model north to model west.
# In mask terms every set bit i moves to (i + 3) % 4.
func _tx_rot(mask: int) -> int:
	var out := 0
	for i in 4:
		if mask & (1 << i):
			out |= 1 << ((i + 3) % 4)
	return out


# A 2x2 stand spans TWO cells of the lane beside it, but only one of them is on
# the stand's lead-in axis. Branching into both drew a tee where the second one
# should have stayed a straight section, pointing at blank pavement with no line
# to meet. So a stand only counts as a connection from the cell its lead-in
# actually runs through.
func _on_stand_leadin(from: Vector2i, stand_cell: Vector2i) -> bool:
	var g = grid.stand_at(stand_cell)
	if g == null:
		return false
	var h: float = grid.stand_park_heading(g)
	if is_nan(h):
		return false
	var perp := Vector2(-sin(h), cos(h))
	var offset: Vector2 = grid.cell_to_world(from) - grid.stand_park_point(g)
	return absf(offset.dot(perp)) < 1.0


func _build_taxiway_tile(cell: Vector2i, centre: Vector2) -> void:
	# Anything an aircraft can taxi ONTO counts as a connection, not just other
	# taxiways: a stand or a runway alongside has to get a branch turning into
	# it. Counting taxiways alone gave the cell beside a stand a straight `mid`
	# piece, which puts its shoulder against the stand — pavement running past
	# the stand rather than turning onto it.
	var want := 0
	for pair in [[Vector2i(0, -1), TX_N], [Vector2i(1, 0), TX_E],
			[Vector2i(0, 1), TX_S], [Vector2i(-1, 0), TX_W]]:
		var d: Vector2i = pair[0]
		var t: int = grid.tile_type(cell + d)
		if t == AirportGrid.TileType.TAXIWAY or t == AirportGrid.TileType.RUNWAY:
			want |= int(pair[1])
		elif t == AirportGrid.TileType.STAND and _on_stand_leadin(cell, cell + d):
			want |= int(pair[1])

	var chosen := ""
	var steps := 0
	for piece in TX_PIECES:
		var m: int = piece["mask"]
		for k in 4:
			if m == want:
				chosen = piece["name"]
				steps = k
				break
			m = _tx_rot(m)
		if chosen != "":
			break
	if chosen == "":
		# An isolated stub matches nothing; a lone `end` still reads correctly.
		chosen = "end"

	# One transform, not a subtree. The mesh itself is welded once by _tx_mesh()
	# and already carries the scale and the half-length offset, so all a tile
	# contributes is where its piece stands and which way it faces.
	#
	# Lifted onto the pavement band. The kit lays its pavement flat at y=0, real
	# aerodrome fashion, which put it exactly coplanar with the ground and lost
	# every z-fight — the taxiways instantiated correctly and drew nothing at all.
	# Which of the four corner shoulders to repaint. See _tx_corner_of.
	var repaint := 0
	for i in 4:
		var corner: int = TX_CORNERS[i]
		# The piece's own corner, carried round to the world by the same rotation
		# the piece itself gets.
		for k in steps:
			corner = _tx_rot(corner)
		var d := Vector2i(1 if corner & TX_E else -1, -1 if corner & TX_N else 1)
		if _tx_is_pavement(cell + d):
			repaint |= 1 << i

	# Part of the key, because the weld is cached and the remap only runs on a
	# miss: two tiles of the same piece with different corners open are two
	# different meshes.
	var mask_key := repaint
	_add_model("tx:%s:%d" % [chosen, repaint], TX_MODELS[chosen], TX_PRE,
		Transform3D(Basis(Vector3.UP, float(steps) * PI * 0.5), w3(centre, H_PAVEMENT)),
		func(node: String, mat: String, box: AABB) -> String:
			if mat != "shoulder_asphalt" or not node.begins_with("shoulder"):
				return mat
			var c := _tx_corner_of(box)
			if c < 0 or not (mask_key & (1 << c)):
				return mat
			# Repainted, NOT dropped. The fillet sharing this corner box is only a
			# quarter-disc; deleting the shoulder around it would leave a crescent
			# of bare ground inside what should read as unbroken pavement.
			return "taxiway_concrete",
		# The kit is ground-plane geometry, and it does not lie perfectly flat: the
		# pavement, its shoulders and the turn fillets are separate slabs at
		# slightly different heights. Under a low sun each fillet's curved edge
		# threw a shadow across the slab beside it, which is the quarter-circle of
		# shade that appeared at junctions and, worst of all, over an apron, where
		# every cell is a crossroads and so has four of them.
		#
		# Flat ground has no business casting a shadow anyway. The kit's signs and
		# edge lights lose theirs too, but they are a couple of units tall and
		# nobody will miss them.
		false)


func _tx_is_pavement(c: Vector2i) -> bool:
	var t: int = grid.tile_type(c)
	return t == AirportGrid.TileType.TAXIWAY or t == AirportGrid.TileType.RUNWAY \
		or t == AirportGrid.TileType.STAND


# Every piece carries a dark asphalt shoulder around the outside of its pavement.
# On the four-way and three-way pieces part of that shoulder is a small square in
# the DIAGONAL corner, filling the outside of the turn's fillet — which is right
# for a junction standing in grass, and wrong in the middle of an apron, where it
# reads as a quarter-circle of shadow dropped on continuous concrete.
#
# So a corner shoulder is repainted as pavement whenever the tile diagonally
# beyond it is pavement too. Identified by geometry rather than by name: the kit's
# names are laid out in its own frame and do not survive the mapping (`corner`
# opens north and west, and `cross`'s "shoulder_sw" sits at its north-west).
#
# Corner order matches TX_CORNERS: 0 NW, 1 NE, 2 SE, 3 SW.
const TX_CORNERS := [TX_N | TX_W, TX_N | TX_E, TX_S | TX_E, TX_S | TX_W]


func _tx_corner_of(box: AABB) -> int:
	var t: float = AirportGrid.TILE
	# Edge strips and end caps run the full length of a side, so bounding both
	# axes is what separates a corner square from them. Sign bases share the
	# shoulder material and are smaller still, which the offset test below drops.
	if box.size.x > t * 0.6 or box.size.z > t * 0.6:
		return -1
	var c: Vector3 = box.position + box.size * 0.5
	if absf(c.x) < t * 0.25 or absf(c.z) < t * 0.25:
		return -1
	if c.z < 0.0:
		return 1 if c.x > 0.0 else 0
	return 2 if c.x > 0.0 else 3


# One ramp per tile, turned so its entrance meets the road. The model's ramp
# landing sits on its +z side, which is the same "local +z is the business end"
# convention the pier mesh uses, so aiming it is one atan2.
#
# 672 meshes, cars included — easily the heaviest model in the game, and the
# reason it goes through the welder like everything else rather than being
# instantiated per car park.
func _build_parking_tile(cell: Vector2i, centre: Vector2) -> void:
	var face := Vector2(0.0, 1.0)
	for d in [Vector2i(0, 1), Vector2i(1, 0), Vector2i(0, -1), Vector2i(-1, 0)]:
		if grid.tile_type(cell + d) == AirportGrid.TileType.ROAD:
			face = Vector2(d)
			break
	_add_model("parking", PARKING_MODEL, Transform3D.IDENTITY,
		Transform3D(Basis(Vector3.UP, atan2(face.x, face.y)), w3(centre, H_PAVEMENT)))


# Does the road carry on into this cell? The map edge counts: that is the airport
# entrance, and stopping half a tile short would leave it hanging in the grass.
# So do car parks, which a road has to actually arrive at.
func _road_links(c: Vector2i) -> bool:
	if not grid.in_bounds(c):
		return true
	var t: int = grid.tile_type(c)
	return t == AirportGrid.TileType.ROAD or t == AirportGrid.TileType.PARKING


# The kit has one piece — a straight, two lanes, running along its local z — so
# every junction is built by laying that piece TWICE, once per axis, and dropping
# whichever of its markings the junction makes wrong.
#
# The trick is that the piece's edge lines run down its two long sides, so the
# north-south copy draws the west and east edges and the east-west copy draws the
# north and south ones. Between them they can draw any subset of the four sides.
# An edge line is kept only where the road does NOT continue, so a corner ends up
# lined along its outside and open on the inside, a crossroads is open all round,
# and a dead end gets closed off. Centre dashes are the mirror image: kept only
# where the road DOES continue, so a stub does not paint dashes into the grass.
#
# Only the first copy brings its asphalt. Two full-tile slabs at the same height
# is a z-fight, and the second one has nothing else to contribute.
func _build_road_tile(cell: Vector2i, centre: Vector2) -> void:
	var link := 0
	for pair in [[Vector2i(0, -1), TX_N], [Vector2i(1, 0), TX_E],
			[Vector2i(0, 1), TX_S], [Vector2i(-1, 0), TX_W]]:
		if _road_links(cell + (pair[0] as Vector2i)):
			link |= int(pair[1])

	for steps in 2:
		# The piece's own sides, carried round to the world by the same rotation
		# the piece gets — exactly as the taxiway corners are.
		var side := {}
		for d in [TX_N, TX_E, TX_S, TX_W]:
			var world: int = d
			for k in steps:
				world = _tx_rot(world)
			side[d] = (link & world) != 0

		var keep_w: bool = not side[TX_W]
		var keep_e: bool = not side[TX_E]
		var keep_n: bool = side[TX_N]
		var keep_s: bool = side[TX_S]
		var slab := steps == 0
		var key := "road:%d:%d%d%d%d%d" % [
			steps, int(keep_w), int(keep_e), int(keep_n), int(keep_s), int(slab)]

		_add_model(key, ROAD_MODEL, ROAD_PRE,
			Transform3D(Basis(Vector3.UP, float(steps) * PI * 0.5),
				w3(centre, H_PAVEMENT)),
			func(node: String, mat: String, box: AABB) -> String:
				var c: Vector3 = box.position + box.size * 0.5
				if node.begins_with("asphalt"):
					return mat if slab else ""
				if node.begins_with("edge_line"):
					# West and east are the piece's own long sides.
					if c.x < 0.0:
						return mat if keep_w else ""
					return mat if keep_e else ""
				if node.begins_with("center_line"):
					if c.z < 0.0:
						return mat if keep_n else ""
					return mat if keep_s else ""
				return mat,
			# Flat ground, same as the taxiway kit: it must not shade itself.
			false)


# Terminals, concourses and stands are each a single authored mesh whose
# footprint IS its size in tiles, so building one is placing one model — no
# merging, no parametric geometry. That is why the grid stores them as
# fixed-size entities rather than as painted tiles.
#
# The pier mesh runs from its link end along +z, so it is laid from the cell that
# meets the terminal outward, and the hall and stand meshes are centred on their
# own footprints.
func _build_terminals() -> void:
	for t in grid.terminals:
		_place_building("terminal", TERMINAL_MODEL, t["cells"], _building_yaw(t["cells"]))
	for c in grid.concourses:
		_place_pier(c)


# Centred on the footprint's middle, turned to run along its long axis.
func _place_building(key: String, model: PackedScene, cells: Array, yaw: float) -> void:
	_add_model(key, model, Transform3D.IDENTITY,
		Transform3D(Basis(Vector3.UP, yaw), w3(_cells_centre(cells))))


# A pier is directional: the mesh's origin is its link, at the end that meets the
# hall, and it extends the length of the building from there. `cells` is stored
# root-first by place_concourse() for exactly this reason.
func _place_pier(c: Dictionary) -> void:
	var cells: Array = c["cells"]
	if cells.size() < 2:
		return
	var dir := Vector2(Vector2i(cells[1]) - Vector2i(cells[0]))
	var t: float = AirportGrid.TILE
	# Start at the root cell's OUTER edge, not its centre, or the pier would sit
	# half a tile short of the hall it is supposed to be joined to.
	var root: Vector2 = grid.cell_to_world(cells[0]) - dir * (t * 0.5)
	# Stretched along the run ONLY. Scaling uniformly happened to work while a
	# pier was four tiles — 128/120.5 is 1.06, and 30 units of width times 1.06 is
	# a hair under the tile it has to fit in — but it was luck, not design: at six
	# tiles the same uniform factor is 1.59, and the pier comes out 1.6 tiles wide,
	# straddling the stands on both flanks.
	#
	# So width and height are pinned to the tile and only depth follows the length.
	#
	# That length varies per pier, so it goes in the INSTANCE transform: every pier
	# on the field shares one welded mesh and stretches it to its own run.
	var size := Vector3(
		AirportGrid.TILE / CONCOURSE_MODEL_W,
		AirportGrid.TILE / CONCOURSE_MODEL_W,
		(float(cells.size()) * t) / CONCOURSE_MODEL_LEN)
	# The mesh's +z maps to the run direction, so local (0,0,1) must land on dir.
	# Rotation THEN scale, matching what Node3D composes from rotation and scale —
	# Basis.scaled() post-multiplies and would skew every pier not laid east-west.
	_add_model("concourse", CONCOURSE_MODEL, Transform3D.IDENTITY, Transform3D(
		Basis(Vector3.UP, atan2(dir.x, dir.y)) * Basis.from_scale(size), w3(root)))


func _cells_centre(cells: Array) -> Vector2:
	var sum := Vector2.ZERO
	for c in cells:
		sum += grid.cell_to_world(c)
	return sum / float(cells.size())


# A footprint wider than it is tall runs east-west; otherwise it is turned a
# quarter. Read off the cells rather than the stored rot so it stays correct for
# anything that ever builds one directly.
func _building_yaw(cells: Array) -> float:
	var lo: Vector2i = cells[0]
	var hi: Vector2i = cells[0]
	for c in cells:
		lo = Vector2i(mini(lo.x, c.x), mini(lo.y, c.y))
		hi = Vector2i(maxi(hi.x, c.x), maxi(hi.y, c.y))
	return 0.0 if (hi.x - lo.x) >= (hi.y - lo.y) else PI * 0.5



func _build_runways() -> void:
	var t: float = AirportGrid.TILE
	for r in grid.runways:
		var a: Vector2 = r["a"]
		var b: Vector2 = r["b"]
		var axis: Vector2 = grid.runway_direction(r)
		# Overrun the ends by half a tile, matching the old renderer.
		var ea := a - axis * (t * 0.5)
		var eb := b + axis * (t * 0.5)
		var length: float = ea.distance_to(eb)
		# A free-angle runway is simply a rotated box here. No rasterization and
		# no eight-compass-point restriction — the reason 3D suits this game
		# better than isometric sprites, which need one sprite per heading.
		var yaw := -axis.angle()
		_add("rwy", "box", _mat("rwy", COL_RUNWAY),
			Vector3(length, H_PAVEMENT, t * RUNWAY_WIDTH_TILES),
			w3((ea + eb) * 0.5, H_PAVEMENT * 0.5), yaw)

		var usable: bool = grid.runway_is_usable(r)
		var mark := _mat("rwymark", COL_MARKING) if usable else _mat("rwybad", Color(1.0, 0.35, 0.35))
		var dashes := maxi(int(length / 24.0), 1)
		for i in dashes:
			var f: float = (float(i) + 0.5) / float(dashes)
			_add("rwymark_" + ("ok" if usable else "bad"), "box", mark,
				Vector3(12.0, 0.6, 1.8), w3(ea.lerp(eb, f), H_MARKING), yaw)

		# Threshold designators, painted on the pavement at each end.
		var ends: Array = grid.runway_end_labels(r)
		_paint_designator(ends[0], ea + axis * (t * 0.9), axis)
		_paint_designator(ends[1], eb - axis * (t * 0.9), -axis)


# Painted flat on the pavement rather than drawn as a screen-space label: it is a
# runway marking, so it belongs to the ground and should rotate with the strip
# and with the camera. `facing` is the direction a departing aircraft is looking,
# which is the direction the numerals must read.
func _paint_designator(text: String, at: Vector2, facing: Vector2) -> void:
	var l := Label3D.new()
	l.text = text
	l.font_size = 128
	l.pixel_size = 0.24
	l.modulate = Color(0.94, 0.94, 0.94)
	l.billboard = BaseMaterial3D.BILLBOARD_DISABLED
	l.double_sided = true
	l.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	l.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	# Lay it flat (-90 about X), then spin it so its "up" runs down the strip.
	l.rotation_degrees = Vector3(-90.0, rad_to_deg(-facing.angle() - PI * 0.5), 0.0)
	l.position = w3(at, H_MARKING)
	_runway_root.add_child(l)


# The tower is bought in the ops panel, not placed with a tool, so nothing in the
# simulation knows where it stands and the renderer has to choose. Pushed through
# a setter rather than read every frame so a facility purchase costs one rebuild,
# not one per frame — and so load, undo and sell all reach it without each having
# to remember to.
func set_tower_count(n: int) -> void:
	if n == _tower_count:
		return
	_tower_count = n
	mark_layout_dirty()


# One building however many units are commissioned. Further units are
# controllers and equipment, not a second tower — two identical towers side by
# side would read as a bug rather than as capacity.
func _build_tower() -> void:
	if _tower_count <= 0 or grid == null:
		return
	var cell := _tower_site()
	if cell == AirportGrid.NOWHERE:
		return
	_add_model("tower", TOWER_MODEL, Transform3D.IDENTITY, Transform3D(
		Basis.from_scale(Vector3.ONE * TOWER_SCALE), w3(grid.cell_to_world(cell))))


# The nearest empty tile to the middle of the movement area that the tower can
# stand on. Scored rather than filtered, so the search always returns something:
# a tile clear of buildings wins, and on a field with no room left it will still
# take one that is not.
#
# Rerun on every layout rebuild, so building over its spot moves it rather than
# leaving a tower standing inside a new taxiway.
func _tower_site() -> Vector2i:
	var focus := _field_focus()
	var best := AirportGrid.NOWHERE
	var best_score := INF
	var b: Rect2i = grid.owned_bounds()
	for y in range(b.position.y, b.position.y + b.size.y):
		for x in range(b.position.x, b.position.x + b.size.x):
			var c := Vector2i(x, y)
			if not grid.is_buildable(c) or grid.tile_type(c) != AirportGrid.TileType.EMPTY:
				continue
			# Two different kinds of penalty, deliberately weighted apart.
			#
			# A building next door is disqualifying, so its weight exceeds any
			# distance the field can produce — the grid's diagonal is about 51
			# cells — and distance only breaks ties within that tier.
			#
			# Pavement next door is merely unwanted: the tower's base is 41 units
			# across against a 32-unit tile, so it overhangs, and against a taxiway
			# that reads as a tower standing in the traffic. But it is worth a few
			# cells of walk, not a trip to the far corner — a flat 6.0 nudge tried
			# once before pushed the tower clean across the runway. Counting SIDES
			# at a small weight caps the whole thing at four cells' distance, which
			# cannot outrun the field.
			var score: float = _tower_clearance_cost(c) + Vector2(c - focus).length()
			if score < best_score:
				best_score = score
				best = c
	return best


# What the tower must stand clear of is *buildings*: against the terminal it read
# as a mast on the roof, and its base spills past its own tile at this scale, so
# it would foul a stand. Taxiways and runways are explicitly not on that list —
# standing over them is the entire job, and an infield site between the apron and
# the parallel taxiway is where a real tower goes.
func _tower_clearance_cost(c: Vector2i) -> float:
	var building := false
	var pavement := 0
	for n in grid.neighbors(c):
		# Annotated, not inferred: `grid` is untyped, so this returns Variant and
		# `:=` fails the "inferred from Variant" check.
		var t: int = grid.tile_type(n)
		# TERMINAL is on this list because it is the case the rule was written for.
		# It was missing: when the old TERMINAL tile was renamed CONCOURSE and a new
		# hall type appended, this kept naming the pier and quietly stopped naming
		# the hall — so the one building the tower must not hug was the one it was
		# free to stand against.
		if t == AirportGrid.TileType.TERMINAL or t == AirportGrid.TileType.CONCOURSE \
				or t == AirportGrid.TileType.STAND \
				or t == AirportGrid.TileType.ROAD or t == AirportGrid.TileType.PARKING:
			building = true
		elif t == AirportGrid.TileType.TAXIWAY or t == AirportGrid.TileType.RUNWAY:
			pavement += 1
	# One walk of the neighbours, not two: this runs for every owned cell on every
	# layout rebuild, and splitting it cost most of a millisecond.
	return (1000.0 if building else 0.0) + float(pavement) * 2.0


# Controllers need sightlines over the movement area, so the tower is drawn to
# the middle of *that* — runways and taxiways — rather than to the terminal it
# used to hug. On the starter layout this lands it in the infield between the
# apron taxiway and the parallel taxiway, out among the runways where a real one
# stands, instead of tucked against the concourse.
#
# Stands, then owned land, are only fallbacks for a field with no pavement yet.
func _field_focus() -> Vector2i:
	var sum := Vector2.ZERO
	var n := 0
	for c in grid.tiles:
		var t: int = grid.tile_type(c)
		if t == AirportGrid.TileType.TAXIWAY or t == AirportGrid.TileType.RUNWAY:
			sum += Vector2(c)
			n += 1
	if n == 0:
		for g in grid.stands:
			for c in g["cells"]:
				sum += Vector2(c)
				n += 1
	if n == 0:
		var b: Rect2i = grid.owned_bounds()
		return b.position + b.size / 2
	return Vector2i((sum / float(n)).round())


# The stand mesh sits ON a coloured pad rather than replacing it. The pad is what
# sync_stands() recolours every frame — free, occupied, orphaned — and the mesh
# carries its own materials, so tinting the model instead would mean overriding
# every surface of 68 meshes per stand per frame.
func _build_stands() -> void:
	var t: float = AirportGrid.TILE
	for g in grid.stands:
		var nodes: Array = []
		for c in g["cells"]:
			nodes.append(_slab(_stand_root, Vector3(t * 0.98, H_STAND, t * 0.98),
				w3(grid.cell_to_world(c), H_STAND * 0.5), _mat("standfree", COL_STAND_FREE)))
		_stand_nodes[g["id"]] = nodes

		# The stand mesh is NOT centred: its jet-bridge collar sits at the model
		# origin and the bridge reaches out along +z, so like the pier it is
		# anchored at the edge that meets the building. Placing it centred put
		# every bridge on the same side of the pier regardless of which flank the
		# stand was on.
		#
		# Orientation is derived, not stored. `stand_park_heading` already points
		# at the pier — or, failing that, away from the taxiway — and reusing it
		# means the bridge and the aircraft nose can never disagree.
		var to_pier := Vector2(0.0, -1.0)
		var h: float = grid.stand_park_heading(g)
		if not is_nan(h):
			to_pier = Vector2(cos(h), sin(h))
		# Laid along stand_park_point's axis, so the painted lead-in lands on a
		# cell centre and meets the taxiway centreline. The stand is two cells
		# DEEP whichever way it is turned, so half of that is one tile — this is
		# the footprint's near edge, against the pier.
		#
		# Local +z must run from that edge back across the stand, away from the
		# pier — the direction the bridge extends to reach the aircraft.
		_add_model("stand", STAND_MODEL, Transform3D.IDENTITY, Transform3D(
			Basis(Vector3.UP, atan2(-to_pier.x, -to_pier.y)),
			w3(grid.stand_park_point(g) + to_pier * t, H_STAND)))


# Stand occupancy flips constantly while the layout does not, so colour is
# refreshed per frame rather than triggering a full static rebuild.
func sync_stands() -> void:
	if grid == null:
		return
	for g in grid.stands:
		if not _stand_nodes.has(g["id"]):
			continue
		var mat: Material
		if not grid.stand_is_connected(g):
			mat = _mat("standorphan", COL_STAND_ORPHAN)
		elif g["occupied"]:
			mat = _mat("standbusy", COL_STAND_BUSY)
		else:
			mat = _mat("standfree", COL_STAND_FREE)
		for mi in _stand_nodes[g["id"]]:
			(mi as MeshInstance3D).material_override = mat


# --- aircraft ---------------------------------------------------------------

func _collect_mesh_instances(n: Node, out: Array) -> void:
	if n is MeshInstance3D:
		out.append(n)
	for child in n.get_children():
		_collect_mesh_instances(child, out)


# The model keeps `livery` as its own named material, separate from `shell`, so
# an airline's colours are a per-instance override rather than a second mesh.
func _tint_livery(root: Node, color: Color) -> void:
	var meshes: Array = []
	_collect_mesh_instances(root, meshes)
	for mi in meshes:
		var mesh: Mesh = mi.mesh
		if mesh == null:
			continue
		for s in mesh.get_surface_count():
			var m: Material = mesh.surface_get_material(s)
			if m == null or m.resource_name != "livery":
				continue
			# Duplicate first: the imported material is shared by every instance
			# of the model, so editing in place repaints the whole fleet.
			var dup: Material = m.duplicate()
			if dup is StandardMaterial3D:
				(dup as StandardMaterial3D).albedo_color = color
			mi.set_surface_override_material(s, dup)


func _livery_for(airline: String) -> Color:
	if _livery_cache.has(airline):
		return _livery_cache[airline]
	# Deterministic per-airline hue, so a carrier keeps its colours across a run
	# without needing an art table.
	var h: float = float(abs(airline.hash()) % 360) / 360.0
	var c := Color.from_hsv(h, 0.62, 0.72)
	_livery_cache[airline] = c
	return c


# The model's nose points down -Z (its vertical stabiliser sits at +Z), which is
# already Godot's forward convention. A 2D heading h has forward (cos h, sin h),
# which maps to 3D (cos h, 0, sin h); solving for the Y rotation that takes -Z
# there gives this.
static func yaw_for_heading(h: float) -> float:
	return -h - PI * 0.5


func _make_plane(class_code: String, airline: String) -> Dictionary:
	var container := Node3D.new()
	_plane_root.add_child(container)

	# Ground ring stays on the pavement even when the aircraft is airborne, so it
	# doubles as a position marker for anything in the air.
	var ring_mesh := TorusMesh.new()
	ring_mesh.inner_radius = 11.0
	ring_mesh.outer_radius = 14.0
	var ring := MeshInstance3D.new()
	ring.mesh = ring_mesh
	ring.position = Vector3(0.0, H_MARKING, 0.0)
	container.add_child(ring)

	var holder := Node3D.new()
	container.add_child(holder)

	var packed = PLANE_MODELS.get(class_code, PLANE_MODELS["N"])
	var model: Node3D = packed.instantiate()
	var s: float = 1.0
	match class_code:
		"R":
			s = 0.7
		"W":
			s = 1.35
	# Divide by THIS model's own length, not a shared constant: the meshes are
	# different real-world sizes, so a single divisor would double-count.
	var own_len: float = float(MODEL_LENGTHS.get(class_code, 40.0))
	model.scale = Vector3.ONE * ((PLANE_LENGTH_PX * s * PLANE_SCALE_FUDGE) / own_len)
	_tint_livery(model, _livery_for(airline))
	holder.add_child(model)

	return {"container": container, "holder": holder, "ring": ring}


## `records` is an array of plain dictionaries, one per aircraft:
##   id, pos (Vector2), heading (float), altitude (float),
##   class_code (String), airline (String), status (Color)
func sync_planes(records: Array) -> void:
	var seen := {}
	for rec in records:
		var id: int = rec["id"]
		seen[id] = true
		if not _plane_nodes.has(id):
			_plane_nodes[id] = _make_plane(rec["class_code"], rec["airline"])
		var n: Dictionary = _plane_nodes[id]

		var container: Node3D = n["container"]
		var holder: Node3D = n["holder"]
		var ring: MeshInstance3D = n["ring"]

		container.position = w3(rec["pos"], 0.0)
		holder.position = Vector3(0.0, H_PAVEMENT + float(rec["altitude"]), 0.0)
		holder.rotation = Vector3(0.0, yaw_for_heading(rec["heading"]), 0.0)

		var status: Color = rec["status"]
		ring.material_override = _mat("ring_" + status.to_html(false), status, true)
		# Airborne aircraft get a pitch-up attitude, which is most of what sells
		# a climb-out at this camera angle.
		holder.rotation.z = deg_to_rad(9.0) if float(rec["altitude"]) > 6.0 else 0.0

	for id in _plane_nodes.keys():
		if seen.has(id):
			continue
		(_plane_nodes[id]["container"] as Node3D).queue_free()
		_plane_nodes.erase(id)


# --- weather ----------------------------------------------------------------
#
# CPUParticles3D rather than GPUParticles3D: the project runs the
# gl_compatibility renderer, where CPU particles are the dependable option.
#
# The emitter is parented to the camera pivot and emits from a flat box above it,
# so precipitation follows the view instead of being a patch of weather sitting
# over one corner of a field the player may have panned away from.

## `kind` is a Regions.WEATHER key, or "" for clear.
func set_weather(kind: String) -> void:
	if kind == _weather_kind:
		return
	_weather_kind = kind

	if _weather != null:
		_weather.queue_free()
		_weather = null
	if kind != "snow" and kind != "storm" and kind != "fog":
		return

	var p := CPUParticles3D.new()
	p.local_coords = false
	p.emission_shape = CPUParticles3D.EMISSION_SHAPE_BOX
	p.emission_box_extents = Vector3(900.0, 4.0, 900.0)
	p.position = Vector3(0.0, 620.0, 0.0)
	p.draw_order = CPUParticles3D.DRAW_ORDER_VIEW_DEPTH

	var mesh := QuadMesh.new()
	var mat := StandardMaterial3D.new()
	mat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	mat.billboard_mode = BaseMaterial3D.BILLBOARD_ENABLED
	mat.vertex_color_use_as_albedo = true

	match kind:
		"snow":
			mesh.size = Vector2(3.4, 3.4)
			mat.albedo_color = Color(1, 1, 1, 0.9)
			p.amount = 1400
			p.lifetime = 7.0
			p.gravity = Vector3(0.0, -70.0, 0.0)
			# Lateral spread makes it drift rather than fall like a curtain.
			p.initial_velocity_min = 8.0
			p.initial_velocity_max = 26.0
			p.direction = Vector3(0.35, -1.0, 0.2)
			p.spread = 28.0
		"storm":
			mesh.size = Vector2(1.1, 13.0)
			mat.albedo_color = Color(0.68, 0.78, 0.92, 0.55)
			p.amount = 2200
			p.lifetime = 2.2
			p.gravity = Vector3(0.0, -900.0, 0.0)
			p.initial_velocity_min = 220.0
			p.initial_velocity_max = 300.0
			p.direction = Vector3(0.18, -1.0, 0.1)
			p.spread = 4.0
		"fog":
			# Fog is not precipitation — a few big, slow, near-transparent puffs
			# drifting through read as murk without hiding the airport.
			mesh.size = Vector2(150.0, 150.0)
			mat.albedo_color = Color(0.78, 0.82, 0.85, 0.10)
			p.amount = 26
			p.lifetime = 26.0
			p.gravity = Vector3.ZERO
			p.initial_velocity_min = 4.0
			p.initial_velocity_max = 12.0
			p.direction = Vector3(1.0, 0.0, 0.3)
			p.spread = 12.0
			p.position = Vector3(0.0, 60.0, 0.0)
			p.emission_box_extents = Vector3(900.0, 40.0, 900.0)

	mesh.material = mat
	p.mesh = mesh
	# Pre-fill, so weather starting does not begin with an empty sky.
	p.preprocess = p.lifetime
	_yaw_node.add_child(p)
	_weather = p


# --- build ghost ------------------------------------------------------------

func clear_ghost() -> void:
	if _ghost_sig == "":
		return
	_ghost_sig = ""
	for c in _ghost_root.get_children():
		c.queue_free()


func set_ghost_cells(cells: Array, color: Color) -> void:
	var sig := "c%s%s" % [color.to_html(false), cells]
	if sig == _ghost_sig:
		return
	_ghost_sig = sig
	for c in _ghost_root.get_children():
		c.queue_free()
	var t: float = AirportGrid.TILE
	var mat := _mat("ghost_" + color.to_html(true), color, true)
	for cell in cells:
		if not grid.in_bounds(cell):
			continue
		_slab(_ghost_root, Vector3(t, H_GHOST, t), w3(grid.cell_to_world(cell), H_GHOST * 0.5), mat)


# A whole parcel as one slab. Emitting 100+ per-cell ghosts for a land purchase
# would be pointless churn every time the cursor moves.
func set_ghost_rect(r: Rect2i, color: Color) -> void:
	var sig := "t%s%s" % [color.to_html(false), r]
	if sig == _ghost_sig:
		return
	_ghost_sig = sig
	for c in _ghost_root.get_children():
		c.queue_free()

	var t: float = AirportGrid.TILE
	var pos: Vector2 = AirportGrid.ORIGIN + Vector2(r.position) * t
	var size: Vector2 = Vector2(r.size) * t
	_slab(_ghost_root, Vector3(size.x, H_GHOST, size.y),
		w3(pos + size * 0.5, H_GHOST * 0.5), _mat("ghost_" + color.to_html(true), color, true))


func set_ghost_runway(a: Vector2, b: Vector2, color: Color) -> void:
	var sig := "r%s%s%s" % [color.to_html(false), a, b]
	if sig == _ghost_sig:
		return
	_ghost_sig = sig
	for c in _ghost_root.get_children():
		c.queue_free()

	var t: float = AirportGrid.TILE
	var axis := b - a
	if axis.length() < 0.001:
		axis = Vector2.RIGHT
	axis = axis.normalized()
	var ea := a - axis * (t * 0.5)
	var eb := b + axis * (t * 0.5)
	_slab(_ghost_root, Vector3(ea.distance_to(eb), H_GHOST, t * 0.84),
		w3((ea + eb) * 0.5, H_GHOST * 0.5), _mat("ghost_" + color.to_html(true), color, true),
		-axis.angle())


# --- camera controls --------------------------------------------------------
#
# Mouse-first, because obscure keys are undiscoverable: drag with the middle or
# right button, wheel to zoom. The keyboard fallbacks are deliberately on keys
# the build tools do not already claim — Main.gd binds T/R/G/H/E/O/P/X to tools
# and 1/2/3, A, D, Space to the sim, so Q/E and WASD are all unavailable.

const ARROW_PAN_PX := 90.0
const ORBIT_SENSITIVITY := 0.35


# Panning is done by measuring how far the ground moved under the cursor and
# undoing exactly that. It needs no trigonometry and stays correct at any yaw,
# pitch or zoom — the hand-rolled version this replaces was none of those.
func _pan_by_screen(delta_px: Vector2) -> void:
	var before := screen_to_world(Vector2.ZERO)
	var after := screen_to_world(delta_px)
	_pan += after - before
	_apply_camera()


func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseButton:
		var mb := event as InputEventMouseButton
		match mb.button_index:
			MOUSE_BUTTON_WHEEL_UP:
				if mb.pressed:
					_zoom = maxf(0.25, _zoom - 0.08)
					_apply_camera()
			MOUSE_BUTTON_WHEEL_DOWN:
				if mb.pressed:
					_zoom = minf(2.5, _zoom + 0.08)
					_apply_camera()
			MOUSE_BUTTON_MIDDLE:
				_panning = mb.pressed
			MOUSE_BUTTON_RIGHT:
				_orbiting = mb.pressed
				# Snap back to a clean isometric angle on release: free rotation
				# feels good to drag but only the 45s actually look isometric.
				if not mb.pressed:
					_yaw_deg = roundf(_yaw_deg / 45.0) * 45.0
					_apply_camera()

	elif event is InputEventMouseMotion:
		var mm := event as InputEventMouseMotion
		if _panning:
			var before := screen_to_world(mm.position - mm.relative)
			var after := screen_to_world(mm.position)
			_pan -= after - before
			_apply_camera()
		elif _orbiting:
			_yaw_deg += mm.relative.x * ORBIT_SENSITIVITY
			_apply_camera()

	elif event is InputEventKey and event.pressed:
		match (event as InputEventKey).keycode:
			KEY_BRACKETLEFT, KEY_COMMA:
				_yaw_deg += 45.0
				_apply_camera()
			KEY_BRACKETRIGHT, KEY_PERIOD:
				_yaw_deg -= 45.0
				_apply_camera()
			KEY_HOME:
				reset_camera()
			KEY_LEFT:
				_pan_by_screen(Vector2(-ARROW_PAN_PX, 0.0))
			KEY_RIGHT:
				_pan_by_screen(Vector2(ARROW_PAN_PX, 0.0))
			KEY_UP:
				_pan_by_screen(Vector2(0.0, -ARROW_PAN_PX))
			KEY_DOWN:
				_pan_by_screen(Vector2(0.0, ARROW_PAN_PX))
